// Auto-generated operator<< for ART enums (normally generated by
// art/tools/generate_operator_out.py during the full ART build).

#include <ostream>
#include "dex/dex_file.h"

namespace art {

std::ostream& operator<<(std::ostream& os, EncodedArrayValueIterator::ValueType code) {
  switch (code) {
    case EncodedArrayValueIterator::ValueType::kByte: os << "kByte"; break;
    case EncodedArrayValueIterator::ValueType::kShort: os << "kShort"; break;
    case EncodedArrayValueIterator::ValueType::kChar: os << "kChar"; break;
    case EncodedArrayValueIterator::ValueType::kInt: os << "kInt"; break;
    case EncodedArrayValueIterator::ValueType::kLong: os << "kLong"; break;
    case EncodedArrayValueIterator::ValueType::kFloat: os << "kFloat"; break;
    case EncodedArrayValueIterator::ValueType::kDouble: os << "kDouble"; break;
    case EncodedArrayValueIterator::ValueType::kMethodType: os << "kMethodType"; break;
    case EncodedArrayValueIterator::ValueType::kMethodHandle: os << "kMethodHandle"; break;
    case EncodedArrayValueIterator::ValueType::kString: os << "kString"; break;
    case EncodedArrayValueIterator::ValueType::kType: os << "kType"; break;
    case EncodedArrayValueIterator::ValueType::kField: os << "kField"; break;
    case EncodedArrayValueIterator::ValueType::kMethod: os << "kMethod"; break;
    case EncodedArrayValueIterator::ValueType::kEnum: os << "kEnum"; break;
    case EncodedArrayValueIterator::ValueType::kArray: os << "kArray"; break;
    case EncodedArrayValueIterator::ValueType::kAnnotation: os << "kAnnotation"; break;
    case EncodedArrayValueIterator::ValueType::kNull: os << "kNull"; break;
    case EncodedArrayValueIterator::ValueType::kBoolean: os << "kBoolean"; break;
    case EncodedArrayValueIterator::ValueType::kEndOfInput: os << "kEndOfInput"; break;
    default: os << "ValueType[" << static_cast<int>(code) << "]"; break;
  }
  return os;
}

}  // namespace art
